// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofickeaxqyfvcpcughrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9maWNrZWF4cXlmdmNwY3VnaHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODYxMzcsImV4cCI6MjA2Mjg2MjEzN30.u9eBb5ryvLwUl5DpC3aCx_0rtP1Al_E_7RDCd7pxsMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);